version: '3'

services:

  registrer:
    image: gitlab/gitlab-runner:latest
    volumes:
      - ./runner-data:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    command: register --non-interactive --executor "shell" --url "YOUR_GITLAB(https://gitlab.com/)" --docker-image alpine:latest --registration-token="YOUR_REGISTRATION_TOKEN" --description="docker-runner" --tag-list="" --run-untagged="true" --locked="false" --access-level="not_protected"
  
  runner:
    image: gitlab/gitlab-runner:latest
    tty: true
    depends_on:
      - registrer
    restart: always
    volumes:
      - ./runner-data:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock