version: '3'

services:

  registrer:
    image: gitlab/gitlab-runner:latest
    volumes:
      - ./entrypoint.sh:/etc/entrypoint.sh
      - ./runner-data:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: /etc/entrypoint.sh
  
  runner:
    image: gitlab/gitlab-runner:latest
    tty: true
    depends_on:
      - registrer
    restart: always
    volumes:
      - ./runner-data:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock